### ISSUE TITLE
Unusable on iPhone7 with iOS 11 beta 9

### ISSUE THREAD

**Issue by vorg** [google-ar/WebARonARKit#11] opened 2017-09-03 14:43 UTC
I'm having problems locking position even for a single cube in the SpawnAtSurface example. I get constant `MISS` errors and cube get's sticky and moves with the screen instead staying out there. Are there any known performance issues or know tricky use cases?

[PlacingObjects](https://developer.apple.com/sample-code/wwdc/2017/PlacingObjects.zip) sample from https://developer.apple.com/arkit/ locks instantly and stays rock solid in the same lighting conditions (carpets, floors, tables, and streets outdoors).

Example of drifting here https://youtu.be/89iou_OGlo0 (from 00:18)

**Comment by judax** [comment] 2017-09-04 14:31
Yes, there are known issues commented in the README. 

1) As we are not able to build on Safari from source we are using a known "hack" layering a native view for the camera feed and ARKit execution and a WKWebView on top for the web content and using a bridge communication between both environments. The bridge is asynchronous so synchronizing the pose and the camera frame with the rendering in WebGL is nearly impossible. Drift may occur.
2) We are not exposing anchors at the moment that will reduce the incorrect poses. We are working on a JS API to improve this.

Some recommendations to see if you can get some better results:
* Try to build the app in release more. In XCode, select the project name (WebARonARKit) from the drop down menu name beside the play/stop buttons and go to "Edit scheme" and then select the "Build configuration" to "release".
* I know is not a great advice but try to test it on a new iPad if possible. Results are much better.

We will work to try to improve these errors. 

On a side note, not detecting the planes should not be a problem with the WebARonARKit technology. ARKit does take indeed some time to both get the tracking going and detecting planes. Try to move around forward/backward, left/right on a plane surface with enough detail (the floor you are using is great indeed).

In XCode you can try to create one of the template examples that come with it "File->New->Project->Augmented Reality App" and we are seeing the same initial tracking issues even in a native app (of course, as mentioned, because the execution of the pose estimation calls and rendering of the video are synchronous, there is no drift).

**Comment by sjovanovic** [comment] 2017-09-08 11:15
Did you try to use getUserMedia() in iOS 11 instead of the native camera stream + transparent webview?

**Comment by judax** [comment] 2017-11-15 22:01
Closing as there has not been much activity to try to reproduce or follow up on this issue.

**Closed by judax** 2017-11-15 22:01 UTC
