### ISSUE TITLE
Camera view not displaying on scene render (iOS 11.3 Beta) 

### ISSUE THREAD

**Issue by bobspecht** [google-ar/WebARonARKit#49] opened 2018-01-26 23:08 UTC
Not sure how much you all care to fix for a beta release, but I just came across this issue. iPhone 7 Plus on iOS 11.3 Beta - 15E5167f.

Camera view doesn't display in "the background" when a scene is loaded. The camera view will briefly flash, then it all goes black – the AR scene still displays (and seems to detect planes).

Did some brief debugging, couldn't find a quick solve. Might be change in the WKWebView?

**Comment by cnsdato** [comment] 2018-01-29 07:22
I can confirm this.
Tested on a iPhone X with iOS 11.3 Beta. Also on an own project without WebARonARKit, I have the same behaviour. It seems the <canvas> element is not longer transparent.

**Comment by DavidArayan** [comment] 2018-01-29 22:22
We don't use this project, however we have the exact same issue. It seems that IOS 11.3 beta does not respect the transparency properties of the GL Canvas. I've created a thread on the issue [https://forums.developer.apple.com/message/291437#291437](url)

**Comment by judax** [comment] 2018-02-01 17:23
Yes, we have seen this issue too. I think Apple is getting the issue from different sources :). Let's hope it can be resolved. Many Cordoba/PhoneGap users are also complaining.

**Comment by cnsdato** [comment] 2018-02-02 11:30
I have made a little demo: https://codepen.io/anon/pen/KQVpMw
If everything works fine you see a half transparent black canvas `gl.clearColor(0.0, 0.0, 0.0, 0.5);` and the underlying red div will shine through.
But on iOS 11.3 in Safari the canvas is full opaque black.

**Comment by cnsdato** [comment] 2018-02-02 12:07
I have filed a apple bugreport and also an Open Radar: https://openradar.appspot.com/radar?id=5018525789847552

**Comment by DavidArayan** [comment] 2018-02-06 22:43
Just like to let you guys know that this issue is still present with the IOS Beta 2 (15E5178f).

**Comment by cnsdato** [comment] 2018-02-07 07:17
@DavidArayan thanks for testing this.

**Comment by judax** [comment] 2018-02-08 16:44
Thanks for the update. We have been seeing the same problem even with the second update of the beta. Hopefully Apple will address this. The most important thing right now is to verify that is a bug, not something they changed deliberately.

**Comment by DavidArayan** [comment] 2018-02-11 22:29
@cnsdato Apologies for the delay. I modified WebARonARKit project to load in your example code, made sure the camera starts up etc.. Results are you see the red border whilst the semi-transparent background is black. Compiled the Code using XCode 9.3 beta running on Iphone X using 11.3 Beta 2 (15E5178f).

**Comment by judax** [comment] 2018-02-15 17:59
As Apple has not mentioned anything about this issue yet, I have tried to solve it temporarily using brut force :). These PRs have been submitted if you are interested in testing them: https://github.com/google-ar/WebARonARKit/pull/53 and https://github.com/google-ar/three.ar.js/pull/100

**Comment by judax** [comment] 2018-02-16 17:29
The PRs have landed. Anyway, I contacted Apple directly and it seems that they know about the issue and will have a fix. I will close this issue. Please, test the new camera frame exposure feature. We might improve it a bit in the near future with multithreading handling, etc but for now, it provides a good baseline,.

**Closed by judax** 2018-02-16 17:29 UTC

**Comment by DavidArayan** [comment] 2018-02-20 22:39
Good news!

Problem seems to be fixed with IOS 11.3 Beta 2 (15E5189f)

**Comment by cnsdato** [comment] 2018-02-21 08:54
@DavidArayan: i think you mean iOS 11.3 Beta **3**

**Comment by DavidArayan** [comment] 2018-02-21 12:13
My apologies, that is indeed what I meant!

**Comment by judax** [comment] 2018-02-22 16:20
Good to know. I reached out to some Apple people I know and they confirmed they knew about the problem and that they did have a fix. Glad to see that they fixed it. Still, I think having the exposure of the camera frames could be a good thing to allow a) perfect synchronization and b) effects on top of the camera (refraction, filters, ...).
